/// <reference types="next" />
/// <reference types="next/image-types/global" />

// NOTE: This file is automatically regenerated by Next.js.
// See https://nextjs.org/docs/app/building-your-application/configuring/typescript
